events {}

http {

    upstream service_a {
        server service-a:3001;
    }

    upstream service_b {
        server service-b:3002;
    }

    upstream service_c {
        server service-c:3003;
    }

    server {

        listen 80;

        location /service-a/ {
            proxy_pass http://service_a/;
        }

        location /service-b/ {
            proxy_pass http://service_b/;
        }

        location /service-c/ {
            proxy_pass http://service_c/;
        }
    }
}
